version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/static:/app/staticfiles
      - media_data:/app/media
    command: ["/bin/bash", "-c", "source venv/bin/activate && ./wait-for-it.sh postgres_db:5432 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./app/static:/app/staticfiles
      - media_data:/app/media
    ports:
      - "443:443"
    depends_on:
      - app

volumes:
  postgres_data:
  media_data: