# Generated by Django 4.2.13 on 2024-05-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_confirmed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
