# Generated by Django 4.2.13 on 2024-05-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_password_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
