# Generated by Django 4.2.13 on 2024-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='original_username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
