# Generated by Django 4.2.13 on 2024-06-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_original_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='original_username',
            new_name='original_username_42',
        ),
    ]
