# Generated by Django 4.2.13 on 2024-07-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='player1_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player2_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='date_played',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
